channels:
- conda-forge
dependencies:
- ase =3.22.1
- coveralls
- coverage
- codacy-coverage
- defusedxml =0.7.1
- h5py =3.9.0
- matplotlib-base =3.7.2
- mendeleev =0.14.0
- mp-api =0.33.3
- numpy =1.24.3
- pandas =2.0.3
- phonopy =2.20.0
- pint =0.22
- pyiron_base =0.6.3
- pymatgen =2023.7.20
- pyscal =2.10.18
- scikit-learn =1.3.0
- scipy =1.11.1
- seekpath =2.1.0
- spglib =2.0.2
- structuretoolkit =0.0.6
- lammps
